app/src/Entity/Offers.php
<?php

namespace App\Entity;

use App\Repository\OffersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: OffersRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Offers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups('searchable')]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    #[Groups('searchable')]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Status $status = null;

    #[ORM\OneToMany(mappedBy: 'offer', targetEntity: Candidacy::class)]
    private Collection $candidacies;

    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Enterprise $enterprise = null;

    #[ORM\Column(length: 255)]
    #[Groups('searchable')]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    #[Groups('searchable')]
    private ?string $department = null;

    #[ORM\ManyToMany(targetEntity: Tags::class, inversedBy: 'offers')]
    #[Groups('searchable')]
    private Collection $tags;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTime();
        $this->candidacies = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    #[ORM\PreUpdate]
    public function updateDate(): void
    {
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, Candidacy>
     */
    public function getCandidacies(): Collection
    {
        return $this->candidacies;
    }

    public function addCandidacy(Candidacy $candidacy): static
    {
        if (!$this->candidacies->contains($candidacy)) {
            $this->candidacies->add($candidacy);
            $candidacy->setOffer($this);
        }

        return $this;
    }

    public function removeCandidacy(Candidacy $candidacy): static
    {
        if ($this->candidacies->removeElement($candidacy)) {
            // set the owning side to null (unless already changed)
            if ($candidacy->getOffer() === $this) {
                $candidacy->setOffer(null);
            }
        }

        return $this;
    }

    public function getEnterprise(): ?Enterprise
    {
        return $this->enterprise;
    }

    public function setEnterprise(?Enterprise $enterprise): static
    {
        $this->enterprise = $enterprise;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): static
    {
        $this->department = $department;

        return $this;
    }

    /**
     * @return Collection<int, Tags>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): static
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(Tags $tag): static
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }
}

app/src/Form/OffersType.php
<?php

namespace App\Form;

use App\Entity\Offers;
use App\Entity\Tags;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OffersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',null,[
                'label' => 'Nom'
            ])
            ->add('city',null,[
                'label' => 'Ville'
            ])
            ->add('department',null,[
                'label' => 'Departement'
            ])
            ->add('tags', EntityType::class, [
                'label' => 'Tags',
                // Entité que l'on veut ajouter au formulaire
                'class' => Tags::class,
                // La valeur que l'on veut ajouter
                'choice_label' => 'tag',
                // Affichage
                'multiple' => true,
                'expanded' => true,
                'attr'=>array(
                    "class" => "flex flex-col"
                )
            ])
            ->add('description', TextareaType::class, [
                'label' => "Description",
                'attr' => [
                    "style" => "height:200px; width:100%;",
                    "class" => "mt-2"
                ]
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Offers::class,
        ]);
    }
}

app/src/Controller/OffersController.php
<?php

namespace App\Controller;

use App\Entity\Candidacy;

use App\Entity\Offers;
use App\Form\OffersType;
use App\Entity\Status;
use App\Entity\Student;
use App\Repository\CandidacyRepository;
use App\Repository\EnterpriseRepository;
use App\Repository\OffersRepository;
use App\Repository\StatusRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/offers')]
class OffersController extends AbstractController
{
    #[Route('/add', name: 'app_offers_create', methods: ['GET', 'POST'])]
    public function create(Request              $request,
                           OffersRepository     $offersRepository,
                           EnterpriseRepository $enterpriseRepository,
                           StatusRepository     $statusRepository): Response
    {
        $newOffer = new Offers();
        $form = $this->createForm(OffersType::class, $newOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $enterprise = $enterpriseRepository->findOneBy(
                ['email' => $this->getUser()->getUserIdentifier()]
            );
            $newOffer->setEnterprise($enterprise);
            $newOffer->setStatus($statusRepository->findOneBy(["status" => "Validée"]));
            $offersRepository->save($newOffer, true);

            return $this->redirectToRoute('app_home');
        }

        return $this->render('offers/new.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/edit/{id}', name: 'app_offers_edit', methods: ['GET', 'POST'])]
    public function edit(Request          $request,
                         Offers           $offer,
                         OffersRepository $offersRepository): Response
    {
        $form = $this->createForm(OffersType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $offersRepository->save($offer, true);
            return $this->redirectToRoute('app_home');
        }

        return $this->render('offers/edit.html.twig', [
            'offer' => $offer,
            'form' => $form
        ]);
    }

    #[Route('/delete/{id}', name: 'app_offers_delete', methods: ['POST'])]
    public function delete(Request             $request,
                           Offers              $offer,
                           OffersRepository    $offersRepository,
                           CandidacyRepository $candidacyRepository): Response
    {
        $candidacies = $offer->getCandidacies();
        foreach ($candidacies as $candidacy) {
            $candidacyRepository->remove($candidacy, true);
        }
        $offersRepository->remove($offer, true);
        // Permet de revenir sur la page précédente
        $route = $request->headers->get('referer');

        return $this->redirect($route);
    }

    #[Route('{id}/apply', name: 'app_offers_apply', methods: ['GET', 'POST'])]
    public function apply(Offers $offer, EntityManagerInterface $entityManager): Response
    {
        $current_user = $this->getUser();

        $student = $entityManager->getRepository(Student::class)->findOneBy(['email' => $current_user->getUserIdentifier()]);

        // Retrieve the "Pending" status from the database
        $status = $entityManager->getRepository(Status::class)->findOneBy(['status' => 'En attente']);

        if (!$status) {
            // Handle the case when the "Pending" status is not found
            throw $this->createNotFoundException('Aucun statut.');
        }

        // Create a new candidacy
        $candidacy = new Candidacy();
        $candidacy->setStudent($student)
            ->setOffer($offer)
            ->setStatus($status);

        // Save the candidacy to the database
        $entityManager->persist($candidacy);
        $entityManager->flush();

        // Redirect to a success page or do further processing as needed
        return $this->redirectToRoute('app_offers_show');
    }

    #[Route('/{id}', name: 'app_offers_show', methods: ['GET'])]
    public function show(Offers $offer): Response
    {
        return $this->render('offers/show.html.twig', [
            'offer' => $offer,
        ]);
    }

}

app/templates/offers/_delete_form.html.twig
<form method="post" action="{{ path('app_offers_delete', {'id': offer.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer cette offre ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offer.id) }}">

    <button type="submit"
       class="text-red-500 flex items-center gap-1 mt-4">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512" class="svg-red">
            <path d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"/>
        </svg>
        <p>Supprimer</p>
    </button>
</form>

app/templates/offers/_form.html.twig
{{ form_start(form) }}
<div class="my-custom-class-for-errors">
    {{ form_errors(form) }}
</div>
        {{ form_row(form.name) }}
        {{ form_row(form.city) }}
        {{ form_row(form.department) }}
        {{ form_label(form.tags) }}
        {{ form_widget(form.tags) }}
        {{ form_row(form.description)}}
<button class="rounded-md p-2 text-white bg-sky-500 hover:bg-sky-600">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

app/templates/offers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title "Modification de votre offre - ARSA" %}

{% block body %}
    <div class="w-3/4 mx-auto">
        <h1 class="w-full text-center">Modification de votre offre</h1>

        <a href="javascript:history.back()">
            <div class="flex items-center gap-3 mb-2">
                <svg width="20" height="auto" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0.439339 10.9393C-0.146447 11.5251 -0.146446 12.4749 0.439341 13.0607L9.98529 22.6066C10.5711 23.1924 11.5208 23.1924 12.1066 22.6066C12.6924 22.0208 12.6924 21.0711 12.1066 20.4853L3.62132 12L12.1066 3.51471C12.6924 2.92892 12.6924 1.97917 12.1066 1.39339C11.5208 0.807603 10.5711 0.807604 9.98527 1.39339L0.439339 10.9393ZM36 10.5L1.5 10.5L1.5 13.5L36 13.5L36 10.5Z"
                          fill="black"/>
                </svg>
                Retour à l'accueil
            </div>
        </a>


        {{ include('offers/_form.html.twig', {'button_label': 'Sauvegarder'}) }}

        <div class="flex mt-1 w-1/4">
            {{ include('offers/_delete_form.html.twig') }}
        </div>

    </div>

{% endblock %}

app/templates/offers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offers index{% endblock %}

{% block body %}
    <h1>Offers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Name</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offer in offers %}
            <tr>
                <td>{{ offer.id }}</td>
                <td>{{ offer.description }}</td>
                <td>{{ offer.name }}</td>
                <td>{{ offer.createdAt ? offer.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ offer.updatedAt ? offer.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_offers_show', {'id': offer.id}) }}">show</a>
                    <a href="{{ path('app_offers_edit', {'id': offer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_offers_new') }}">Create new</a>
{% endblock %}

app/templates/offers/new.html.twig
{% extends 'base.html.twig' %}

{% block title "Création d'une offre - ARSA" %}

{% block body %}


<div class="w-3/4 mx-auto">
    <h1 class="text-center">Création d'une offre</h1>
    <div class="mt-2 mb-3">
        <a href="javascript:history.back()" class="rounded-md p-2 text-white bg-sky-500 hover:bg-sky-600">Retour à la liste</a>
    </div>
    {{ include('offers/_form.html.twig') }}
    <div class="mt-2">
        <a href="javascript:history.back()" class="rounded-md p-2 text-white bg-sky-500 hover:bg-sky-600">Retour à la liste</a>
    </div>

</div>

{% endblock %}

app/templates/offers/show.html.twig
{% extends 'base.html.twig' %}

{% block title "Détail de l'offre - ARSA" %}

{% block body %}

    {% set currentDate = "now"|date("Y-m-d") %}
    {% set offerCreationDate = offer.createdAt|date("Y-m-d") %}
    {% set dateInterval = date('now').diff(offer.createdAt).format('%H:%I:%S') %}
    {% set diffInWeeks = dateInterval|number_format % 7 %}

    <div class="w-3/4 mx-auto">
        <a href="{{ path('app_home') }}">
            <div class="flex items-center gap-3 mb-2">
                <svg width="20" height="auto" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0.439339 10.9393C-0.146447 11.5251 -0.146446 12.4749 0.439341 13.0607L9.98529 22.6066C10.5711 23.1924 11.5208 23.1924 12.1066 22.6066C12.6924 22.0208 12.6924 21.0711 12.1066 20.4853L3.62132 12L12.1066 3.51471C12.6924 2.92892 12.6924 1.97917 12.1066 1.39339C11.5208 0.807603 10.5711 0.807604 9.98527 1.39339L0.439339 10.9393ZM36 10.5L1.5 10.5L1.5 13.5L36 13.5L36 10.5Z"
                          fill="black"/>
                </svg>
                Retour à l'accueil
            </div>
        </a>

        <div class="flex flex-col drop-shadow ">
            <div class="flex flex-row justify-between items-center bg-card-bg-normal p-4  rounded-t-lg ">

                <div class="flex flex-row items-center gap-3">
                    <img src="{{ asset(img_enterprises ~ offer.enterprise.imageName) }}"
                         class="float-right rounded-full"
                         style="width: 40px; height: auto ; margin-right:10px" alt="">
                    <div class="flex flex-col">
                        <p>{{ offer.name }}</p>
                        <p class="mb-2 text-sm font-semibold text-gray-700">{{ offer.enterprise.name }}</p>
                        <p class="text-xs text-gray-500 font-light">{{ offer.city }} ({{ offer.department }})</p>
                        <p class="text-sm text-gray-500 font-normal">Parue il y a {{ diffInWeeks }} semaine(s)</p>
                    </div>
                </div>

                <div class="flex flex-col text-end">
                <span class="text-sm font-medium text-gray-500 mb-1">
                    Il y a {{ offer.candidacies|length }} candidature(s) pour cette offre.
                </span>
                    <span class="text-xs text-gray-500 font-light">
                    Créée le {{ offer.updatedAt ? offer.updatedAt|date('d-m-Y') : '' }}
                </span>
                </div>
            </div>

            <div class="pt-4 pb-4 pl-4 pr-4 rounded-b-lg gap-3 bg-white">

                <div class="flex flex-wrap ">
                    {% for tag in offer.tags %}
                        <span class="rounded-full bg-card-bg-normal }} pl-3 pr-3 mr-2 mb-3 break-keep">{{ tag.tag }}</span>
                    {% endfor %}
                </div>

                <p class="mt-4 mb-4">
                    {{ offer.description }}
                </p>

                {% if app.user %}
                    {% if "ROLE_STUDENT" in app.user.roles %}
                        {% set find = false %}


                        {% for candidacy in offer.candidacies %}
                            {% if candidacy.student.user.id == app.user.id %}
                                {% set find = true %}
                            {% endif %}
                        {% endfor %}


                        {% if find %}
                            <a href="{{ path('app_delete_candidacy', { 'id': offer.id }) }}"
                               class="text-red-500 flex items-center gap-1 mt-4">
                                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"
                                     class="svg-red">
                                    <path d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"/>
                                </svg>
                                <p>Désister</p>
                            </a>


                        {% else %}
                            <a href="{{ path('app_new_candidacy', { 'id': offer.id }) }}"
                               class="text-purple-500 break-keep flex flex-row items-center gap-1 mt-4">
                                <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"
                                     class="svg-purple">
                                    <path d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z"/>
                                </svg>
                                <p>Postuler</p>
                            </a>
                        {% endif %}


                    {% elseif "ROLE_ENTERPRISE" in app.user.roles %}
                        {% if offer.enterprise.id == app.user.enterprise.id %}
                            <div class="flex gap-3">
                                <a href="{{ path("app_offers_edit", {'id': offer.id}) }}"
                                   class="text-purple-500 flex items-center gap-1 mt-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"
                                         class="svg-purple">
                                        <path d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z"/>
                                    </svg>
                                    <p>Modifier</p>
                                </a>
                                {{ include('offers/_delete_form.html.twig') }}
                            </div>
                        {% endif %}
                    {% endif %}

                    <p class="text-sm text-gray-500 mt-4">
                        {% if offer.candidacies|length != 0
                            and "ROLE_ENTERPRISE" in app.user.roles
                            and offer.enterprise.id == app.user.enterprise.id %}
                            <span class="font-semibold">
                            <a href="{{ path('app_enterprise_offers_candidacies', { 'id': offer.id }) }}">
                                Voir les candidatures
                            </a>
                        </span>
                        {% endif %}
                    </p>
                {% endif %}


            </div>
        </div>
    </div>


{% endblock %}